SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


TRUNCATE TABLE `wp_chained_questions`;
INSERT INTO `wp_chained_questions` (`id`, `quiz_id`, `title`, `question`, `qtype`, `soap_type`, `rank`, `autocontinue`, `sort_order`, `accept_comments`, `accept_comments_label`) VALUES
(308, 20, '3', 'Have people annoyed you by criticizing your drinking?', 'radio', 's', 0, 0, 3, 0, 'Your comments:'),
(309, 20, '4', 'Have you ever felt guilty about drinking?', 'radio', 's', 0, 0, 4, 0, 'Your comments:'),
(310, 20, '5', 'Have you ever felt you needed a drink first thing in the morning to steady your nerves or to get rid of a hangover?', 'radio', 's', 0, 0, 5, 0, 'Your comments:'),
(306, 20, '1', 'How many alcoholic drinks do you have per week?', 'text', 's', 0, 0, 1, 0, 'Your comments:'),
(307, 20, '2', 'Have you ever felt you needed to cut down on your drinking?', 'radio', 's', 0, 0, 2, 0, 'Your comments:'),
(305, 19, '9', 'How often do you have thoughts that you would be better off dead, or thoughts of hurting yourself in some way?', 'radio', 's', 0, 0, 9, 0, 'Your comments:'),
(304, 19, '8', 'How often do you move or speak so slowly that other people could have noticed? Or so fidgety or restless that you have been moving a lot more than usual?', 'none', 's', 0, 0, 8, 0, 'Your comments:'),
(302, 19, '6', 'How often do you feel bad about yourself- or that you are a failure or have let yourself or your family down?', 'radio', 's', 0, 0, 6, 0, 'Your comments:'),
(303, 19, '7', 'How often do you have trouble concentrating on things, such as reading the newspaper or watching television?', 'radio', 's', 0, 0, 7, 0, 'Your comments:'),
(301, 19, '5', 'How often do you have a poor appetite or overeat?', 'radio', 's', 0, 0, 5, 0, 'Your comments:'),
(16, 3, 'Lab Input: Endocrine Values', '', 'radio', NULL, 0, 0, 5, 0, 'Your comments:'),
(22, 3, 'Lab Input: HLA and Gluten Antibody', 'Please input HLA and gluten antibody level.', 'radio', NULL, 0, 0, 11, 0, 'Your comments:'),
(85, 10, 'Complaint 4: Weight', 'Related to your weight change, fatigue, or drinking lots of water: Which of the following symptoms are you experiencing?\r\n\r\n(Select all that apply)', 'checkbox', NULL, 0, 0, 3, 0, 'Your comments:'),
(84, 10, 'Complaint 1: Pins/Needles Follow-Up', 'Please tell us where you are feeling these pins/needles sensations.\r\n\r\n(Select all that apply)', 'radio', NULL, 0, 0, 2, 0, 'Your comments:'),
(14, 3, 'Diagnosis: Psychogenic', 'Is the patient psychogenic?', 'radio', NULL, 0, 0, 3, 0, 'Your comments:'),
(15, 3, 'Lab Input: C. Diff Culture', 'Lab input clostridium difficile culture results.', 'radio', NULL, 0, 0, 4, 0, 'Your comments:'),
(17, 3, 'Lab Input: KUB and Colonoscopy', 'Order kidney, ureter, and bladder radiography with colonoscopy.', 'text', NULL, 0, 0, 6, 0, 'Your comments:'),
(18, 3, 'Lab Input: Leukocyte and Lactoferrin Count', 'Please input the leukocyte and lactoferrin counts in the box below.', 'radio', NULL, 0, 0, 7, 1, 'Leukocyte and lactoferrin count:'),
(19, 3, 'Lab Input: KUB', 'KUB results.', 'radio', NULL, 0, 0, 8, 0, 'Your comments:'),
(20, 3, 'Lab Input: Culture', 'What is the result of the culture?', 'radio', NULL, 0, 0, 9, 0, 'Your comments:'),
(21, 3, 'Lab Input: CEA Level', 'Please input CEA level.', 'radio', NULL, 0, 0, 10, 0, 'Your comments:'),
(12, 3, 'Patient Input: Consistency', 'What is the consistency of your diarrhea?', 'radio', NULL, 0, 0, 1, 0, 'Your comments:'),
(13, 3, 'Lab Input: Fasting Trial Stool Sample', 'Try fasting with no food for the next 8 hours. Collect a stool sample and send to the lab. Once your results are received enter them here.', 'radio', NULL, 0, 0, 2, 0, 'Your comments:'),
(23, 3, 'Lab Input: Sudan Stain', 'Input sudan stain result.', 'text', NULL, 0, 0, 12, 0, 'Sudan Stain:'),
(24, 3, 'Lab Input: Albumin', 'Input patient albumin level.', 'text', NULL, 0, 0, 13, 0, ''),
(25, 3, 'Patient: Issues', 'Pulmonary issues, pancreatic issues, sweat issues, dx of cf?', 'radio', NULL, 0, 0, 14, 0, 'Your comments:'),
(26, 3, 'Patient: Certain Foods', 'Does patient experience symptoms after eating certain foods?', 'radio', NULL, 0, 0, 15, 0, 'Your comments:'),
(27, 3, 'Lab Input: Flexible Sigmoidoscopy', 'Lab input results of Flexible Sigmoidoscopy.', 'radio', NULL, 0, 0, 16, 0, 'Your comments:'),
(28, 3, 'Input: Crohn\\\'s Disease Activity Index', 'Submit patient Crohn disease activity index.', 'radio', NULL, 0, 0, 17, 0, 'Your comments:'),
(300, 19, '4', 'How often do you feel tired or have little energy?', 'radio', 's', 0, 0, 4, 0, 'Your comments:'),
(299, 19, '3', 'How often do you have trouble falling or staying asleep, or sleeping too much?', 'radio', 's', 0, 0, 3, 0, 'Your comments:'),
(298, 19, '2', 'How often do you feel down, depressed or hopeless?', 'none', 's', 0, 0, 2, 0, 'Your comments:'),
(297, 19, '1', 'How often do you have little interest or pleasure in doing things?', 'radio', 's', 0, 0, 1, 0, 'Your comments:'),
(293, 18, '4', 'How often do you have trouble relaxing?', 'radio', 's', 0, 0, 4, 0, 'Your comments:'),
(294, 18, '5', 'How often are you so restless that its hard to sit still?', 'radio', 's', 0, 0, 5, 0, 'Your comments:'),
(295, 18, '6', 'How often are you easily annoyed or irritable?', 'radio', 's', 0, 0, 6, 0, 'Your comments:'),
(296, 18, '7', 'How often do you feel afraid as if something awful might happen?', 'radio', 's', 0, 0, 7, 0, 'Your comments:'),
(292, 18, '3', 'How often do you worry too much about different things?', 'radio', 's', 0, 0, 3, 0, 'Your comments:'),
(290, 18, '1', 'Every week, how often do you feel nervous, anxious or on edge?', 'radio', 's', 0, 0, 1, 0, 'Your comments:'),
(291, 18, '2', 'How often are you unable to stop or control your worrying?', 'radio', '', 0, 0, 2, 0, 'Your comments:'),
(288, 17, 'Do you take Medication', 'Do you take medication for your blood pressure?', 'radio', 's', 0, 1, 1, 0, 'Your comments:'),
(289, 17, 'What Medication', 'List your current <span style=\\\"text-decoration: underline;\\\"><strong>hypertension</strong></span> medications', 'text', 's', 0, 0, 2, 0, 'Your comments:'),
(287, 17, 'average bp_manual', 'What is your average blood pressure range? (If either systolic or diastolic number is higher than the range below, use the higher number)', 'radio', 's', 0, 0, 7, 0, 'Your comments:'),
(286, 17, 'Average bp_automated', 'What is your average blood pressure range? (If either systolic or diastolic number is higher than the range below, use the higher number)', 'radio', 's', 0, 0, 6, 0, 'Your comments:'),
(283, 17, 'Check blood pressure?', 'Do you check your blood pressure?', 'radio', 's', 0, 0, 3, 0, 'Your comments:'),
(284, 17, 'How often', 'How often do you check your blood pressure?', 'radio', 's', 0, 0, 4, 0, 'Your comments:'),
(282, 16, '2_type in', 'Please provide feedback below. All comments, suggestions and recommendations are greatly appreciated.', 'text', '', 0, 0, 2, 0, 'Your comments:'),
(267, 15, 'Hospitalization 2: Why?', '', 'text', 's', 0, 0, 20, 0, 'Your comments:'),
(268, 15, 'Hospitalizations: Consent for patient records', 'Do you give us consent to request medical records from this hospitalization?', 'radio', 's', 0, 1, 21, 0, 'Your comments:'),
(269, 15, 'Hospitalization 5: Any other physicians?', 'Have you seen any other physicians since your last appointment here?', 'radio', 's', 0, 1, 22, 0, 'Your comments:'),
(270, 15, 'Hospitalization 6: Who?', '', 'text', 's', 0, 0, 23, 0, 'Your comments:'),
(271, 15, 'Provider: Consent for medical records', 'Do you give consent for us to request medical records from your provider visit?', 'radio', 's', 0, 1, 24, 0, 'Your comments:'),
(272, 15, 'Appoint 1: Smoker?', 'Do you smoke?', 'radio', 's', 0, 1, 25, 0, 'Your comments:'),
(273, 15, 'Appoint 2: Recent retinal exam?', 'Have you gotten a retinal exam within the last 2 years?', 'radio', 's', 0, 1, 26, 0, 'Your comments:'),
(274, 15, 'Appoint 3: Podiatry?', 'Have you seen a podiatrist within the last year?', 'radio', 's', 0, 1, 27, 0, 'Your comments:'),
(275, 15, 'Appoint 4: Dentist?', 'Have you seen a dentist within the last year?', 'radio', 's', 0, 1, 28, 0, 'Your comments:'),
(276, 15, 'Finish (for the type in final answer)', 'Thank you', 'radio', '', 0, 0, 29, 0, 'Your comments:'),
(277, 15, 'v2_Any other complaints', 'Any other complaints?', 'radio', '', 0, 0, 30, 0, 'Your comments:'),
(278, 15, 'Non insulin medication', 'What medications are you taking?', 'text', 's', 0, 0, 31, 0, 'Your comments:'),
(266, 15, 'Hospitalization 1: Since last provider?', 'Have you had any hospitalizations or emergency room (ER) visits since you last saw your provider?', 'radio', 's', 0, 1, 19, 0, 'Your comments:'),
(140, 9, 'Subjective Text Question', 'Were you hospitalized?', 'text', 's', 0, 0, 1, 0, 'Your comments:'),
(86, 10, 'Sugar 1: Glucose check?', 'Are you checking your glucose levels?', 'radio', NULL, 0, 1, 4, 0, 'Your comments:'),
(87, 10, 'Sugar 2: Check Frequency', 'How often are you checking your glucose level?', 'radio', NULL, 0, 1, 5, 0, 'Your comments:'),
(88, 10, 'Sugar 4: Glucose Range?', 'What is your blood glucose range?', 'radio', NULL, 0, 1, 6, 0, 'Your comments:'),
(89, 10, 'Sugar 3: When? (for once per day)', 'When do you check your glucose?', 'radio', NULL, 0, 1, 7, 0, 'Your comments:'),
(90, 10, 'Sugar 3: When? (for multiple times)', 'When do you check your glucose level?', 'radio', NULL, 0, 1, 8, 0, 'Your comments:'),
(91, 10, 'EMR 1: Comorbidities?', 'Do you have any of the following comorbidities?\r\n\r\n(Select all that apply)', 'checkbox', NULL, 0, 0, 9, 0, 'Your comments:'),
(92, 10, 'Hospitalization 1: Since last provider?', 'Have you had any hospitalizations or emergency room (ER) visits since you last saw your provider?', 'radio', NULL, 0, 1, 10, 0, 'Your comments:'),
(93, 10, 'Hospitalization 2: Why?', 'Why were you hospitalized?', 'text', NULL, 0, 0, 11, 0, 'Your comments:'),
(94, 10, 'Hospitalization 3: Where?', 'Where were you hospitalized?', 'text', NULL, 0, 0, 12, 0, 'Your comments:'),
(95, 10, 'Hospitalization 4: When?', 'When were you hospitalized? (Please use DDMMYYYY)', 'text', NULL, 0, 0, 13, 0, 'Your comments:'),
(96, 10, 'Appoint 1: Smoker?', 'Do you smoke?', 'radio', NULL, 0, 1, 14, 0, 'Your comments:'),
(97, 10, 'Appoint 2: Recent retinal exam?', 'Have you gotten a retinal exam within the last 2 years?', 'radio', NULL, 0, 1, 15, 0, 'Your comments:'),
(98, 10, 'Appoint 3: Podiatry?', 'Have you seen a podiatrist within the last year?', 'radio', NULL, 0, 1, 16, 0, 'Your comments:'),
(99, 10, 'Appoint 4: Dentist?', 'Have you seen a dentist within the last year?', 'radio', NULL, 0, 1, 17, 0, 'Your comments:'),
(100, 10, 'Appoint 5: Medication?', 'Are you taking any diabetes medication?', 'radio', NULL, 0, 1, 18, 0, 'Your comments:'),
(101, 10, 'Appoint 6: Following medication instruction?', 'Are you taking your medication as instructed?', 'radio', NULL, 0, 1, 19, 0, 'Your comments:'),
(102, 10, 'Appoint 7: Understand medication instruction?', 'Do you understand the instructions for the medication?', 'radio', NULL, 0, 0, 20, 0, 'Your comments:'),
(103, 10, 'Complaint 1: Choose Complaints', 'Do you have any of the following complaint symptoms?', 'radio', NULL, 0, 0, 1, 0, 'Your comments:'),
(104, 10, 'Any other complaints?', 'Any other complaints?', 'radio', NULL, 0, 0, 21, 0, 'Your comments:'),
(105, 10, 'Blood Glucose Range? _postprandial_', 'What is your average post meal blood glucose?', 'radio', NULL, 0, 0, 22, 0, 'Your comments:'),
(107, 11, 'Complaint 1: Pins/Needles Follow-Up', 'Please tell us where you are feeling these pins/needles sensations. Choose all that apply:\r\n\r\n&nbsp;', 'checkbox', 's', 0, 0, 3, 0, 'Your comments:'),
(108, 11, 'Complaint 4: Constitutional Symptoms', 'Related to your weight change, fatigue, or drinking lots of water: Which of the following symptoms are you experiencing?\r\n\r\n(Select all that apply)', 'checkbox', 's', 0, 0, 4, 0, 'Your comments:'),
(109, 11, 'Sugar 1: Glucose check?', 'Are you checking your glucose levels?', 'radio', 's', 0, 1, 11, 0, 'Your comments:'),
(110, 11, 'Sugar 2: Check Frequency', 'How often are you checking your glucose level?', 'radio', 's', 0, 1, 13, 0, 'Your comments:'),
(111, 11, 'Sugar 4: Glucose Range?', 'What is your blood glucose range?', 'radio', 's', 0, 1, 14, 0, 'Your comments:'),
(112, 11, 'Sugar 3: When? (for once per day)', 'When do you check your glucose?', 'radio', 's', 0, 1, 15, 0, 'Your comments:'),
(113, 11, 'Sugar 3: When? (for multiple times)', 'When do you check your glucose level?', 'radio', 's', 0, 1, 16, 0, 'Your comments:'),
(114, 11, 'EMR 1: Comorbidities?', 'Do you have any of the following comorbidities?\r\n\r\n(Select all that apply)', 'checkbox', 's', 0, 0, 19, 0, 'Your comments:'),
(115, 11, 'Hospitalization 1: Since last provider?', 'Have you had any hospitalizations or emergency room (ER) visits since you last saw your provider?', 'radio', 's', 0, 1, 20, 0, 'Your comments:'),
(116, 11, 'Hospitalization 2: Why?', '', 'text', 's', 0, 0, 21, 0, 'Your comments:'),
(181, 11, 'Not checking gluc:why?', '', 'text', 's', 0, 0, 12, 0, 'Your comments:'),
(119, 11, 'Appoint 1: Smoker?', 'Do you smoke?', 'radio', 's', 0, 1, 31, 0, 'Your comments:'),
(120, 11, 'Appoint 2: Recent retinal exam?', 'Have you gotten a retinal exam within the last 2 years?', 'radio', 's', 0, 1, 32, 0, 'Your comments:'),
(121, 11, 'Appoint 3: Podiatry?', 'Have you seen a podiatrist within the last year?', 'radio', 's', 0, 1, 33, 0, 'Your comments:'),
(122, 11, 'Appoint 4: Dentist?', 'Have you seen a dentist within the last year?', 'radio', 's', 0, 1, 34, 0, 'Your comments:'),
(123, 11, 'Appoint 5: Medication?', 'Are you taking any diabetes medication?', 'radio', 's', 0, 1, 7, 0, 'Your comments:'),
(124, 11, 'Appoint 6: Following medication instruction?', 'Are you taking your medication as instructed?', 'radio', 's', 0, 1, 8, 0, 'Your comments:'),
(125, 11, 'Appoint 7: Why not?', 'Why not?', 'radio', 's', 0, 1, 9, 0, 'Your comments:'),
(131, 11, 'Type in', 'Type in:', 'text', 's', 0, 0, 10, 0, 'Your comments:'),
(126, 11, 'Complaint 1: Choose Complaints', 'Do you have any of the following complaint symptoms?', 'radio', 's', 0, 0, 2, 0, 'Your comments:'),
(127, 11, 'Any other complaints?', 'Any other complaints?', 'radio', 's', 0, 0, 6, 0, 'Your comments:'),
(128, 11, 'Blood Glucose Range? _postprandial_', 'What is your average post meal blood glucose?', 'radio', 's', 0, 0, 18, 0, 'Your comments:'),
(129, 11, 'Other: type in', '', 'text', 's', 0, 0, 5, 0, 'Your comments:'),
(130, 11, 'Hospitalization 5: Any other physicians?', 'Have you seen any other physicians since your last appointment here?', 'radio', 's', 0, 1, 25, 0, 'Your comments:'),
(132, 11, 'Hospitalization 6: Who?', '', 'text', 's', 0, 0, 26, 0, 'Your comments:'),
(180, 11, 'Provider: Consent for medical records', 'Do you give consent for us to request medical records from your provider visit?', 'radio', 's', 0, 1, 29, 0, 'Your comments:'),
(178, 11, 'Study ID', '', 'text', 'n', 0, 0, 1, 0, 'Your comments:'),
(179, 11, 'Hospitalizations: Consent for patient records', 'Do you give us consent to request medical records from this hospitalization?', 'radio', 's', 0, 1, 24, 0, 'Your comments:'),
(136, 11, 'Finish (for the type in final answer)', 'Thank you', 'radio', NULL, 0, 0, 35, 0, 'Your comments:'),
(265, 15, 'EMR 1: Comorbidities?', 'Do you have any of the following comorbidities?\r\n\r\n(Select all that apply)', 'checkbox', 's', 0, 0, 18, 0, 'Your comments:'),
(176, 11, 'v2_Any other complaints', 'Any other complaints?', 'radio', '', 0, 0, 36, 0, 'Your comments:'),
(182, 9, 'Objective Text Question', 'Who is your primary care provider?', 'text', 'o', 0, 0, 2, 0, 'Your comments:'),
(183, 9, 'Checkboxes', 'Which of the following ailments do you have?', 'checkbox', 's', 0, 0, 3, 0, 'Your comments:'),
(184, 9, 'Objective Yes or No', 'Select YES or NO.', 'radio', 'o', 0, 0, 4, 0, 'Your comments:'),
(185, 11, 'Non insulin medication', 'What medications are you taking?', 'text', 's', 0, 0, 37, 0, 'Your comments:'),
(264, 15, 'Blood Glucose Range? _postprandial_', 'What is your average post meal blood glucose?', 'radio', 's', 0, 0, 17, 0, 'Your comments:'),
(263, 15, 'Sugar 3: When? (for multiple times)', 'When do you check your glucose level?', 'radio', 's', 0, 1, 16, 0, 'Your comments:'),
(262, 15, 'Sugar 3: When? (for once per day)', 'When do you check your glucose?', 'radio', 's', 0, 1, 15, 0, 'Your comments:'),
(261, 15, 'Sugar 4: Glucose Range?', 'What is your blood glucose range?', 'radio', 's', 0, 1, 14, 0, 'Your comments:'),
(260, 15, 'Sugar 2: Check Frequency', 'How often are you checking your glucose level?', 'radio', 's', 0, 1, 13, 0, 'Your comments:'),
(259, 15, 'Not checking gluc:why?', '', 'text', 's', 0, 0, 12, 0, 'Your comments:'),
(256, 15, 'Appoint 7: Why not?', 'Why not?', 'radio', 's', 0, 1, 9, 0, 'Your comments:'),
(258, 15, 'Sugar 1: Glucose check?', 'Are you checking your glucose levels?', 'radio', 's', 0, 1, 11, 0, 'Your comments:'),
(257, 15, 'Type in', 'Type in:', 'text', 's', 0, 0, 10, 0, 'Your comments:'),
(254, 15, 'Appoint 5: Medication?', 'Are you taking any diabetes medication?', 'radio', 's', 0, 1, 7, 0, 'Your comments:'),
(255, 15, 'Appoint 6: Following medication instruction?', 'Are you taking your medication as instructed?', 'radio', 's', 0, 1, 8, 0, 'Your comments:'),
(252, 15, 'Other: type in', '', 'text', 's', 0, 0, 5, 0, 'Your comments:'),
(253, 15, 'Any other complaints?', 'Any other complaints?', 'radio', 's', 0, 0, 6, 0, 'Your comments:'),
(251, 15, 'Complaint 4: Constitutional Symptoms', 'Related to your weight change, fatigue, or drinking lots of water: Which of the following symptoms are you experiencing?\r\n\r\n(Select all that apply)', 'checkbox', 's', 0, 0, 4, 0, 'Your comments:'),
(285, 17, 'Method of checking', 'How do you check your blood pressure?', 'radio', 's', 0, 0, 5, 0, 'Your comments:'),
(249, 15, 'Complaint 1: Choose Complaints', 'Do you have any of the following complaint symptoms?', 'radio', 's', 0, 0, 2, 0, 'Your comments:'),
(250, 15, 'Complaint 1: Pins/Needles Follow-Up', 'Please tell us where you are feeling these pins/needles sensations. Choose all that apply:\r\n\r\n&nbsp;', 'checkbox', 's', 0, 0, 3, 0, 'Your comments:'),
(175, 12, '3_lost weight', 'Have you lost weight in the last week?', 'radio', 's', 0, 0, 4, 0, 'Your comments:'),
(174, 12, '3_Exercise', 'Are you exercising at least 30 minutes of moderate intensity activity 5-7 days per week?', 'radio', 's', 0, 1, 3, 0, 'Your comments:'),
(172, 12, '1_BMI?', 'What is your BMI?', 'radio', 's', 0, 1, 1, 0, 'Your comments:'),
(173, 12, '2_Calorie intake', 'What is your average daily calorie intake?', 'radio', 's', 0, 1, 2, 0, 'Your comments:');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
